//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kentico.Components.Web.Mvc.InlineEditors.App_Data.Global.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Kentico_InlineEditor_RichText {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Kentico_InlineEditor_RichText() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Kentico.Components.Web.Mvc.InlineEditors.App_Data.Global.Resources.Kentico.Inline" +
                            "Editor.RichText", typeof(Kentico_InlineEditor_RichText).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insert.
        /// </summary>
        internal static string Kentico_InlineEditor_RichText_MacroPlugin_ActionButton_Insert {
            get {
                return ResourceManager.GetString("Kentico.InlineEditor.RichText.MacroPlugin.ActionButton.Insert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        internal static string Kentico_InlineEditor_RichText_MacroPlugin_ActionButton_Save {
            get {
                return ResourceManager.GetString("Kentico.InlineEditor.RichText.MacroPlugin.ActionButton.Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configure.
        /// </summary>
        internal static string Kentico_InlineEditor_RichText_MacroPlugin_Command_ConfigureMacro {
            get {
                return ResourceManager.GetString("Kentico.InlineEditor.RichText.MacroPlugin.Command.ConfigureMacro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact attribute.
        /// </summary>
        internal static string Kentico_InlineEditor_RichText_MacroPlugin_Command_ContactAttribute {
            get {
                return ResourceManager.GetString("Kentico.InlineEditor.RichText.MacroPlugin.Command.ContactAttribute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insert Dynamic Text.
        /// </summary>
        internal static string Kentico_InlineEditor_RichText_MacroPlugin_Command_InsertDynamicText {
            get {
                return ResourceManager.GetString("Kentico.InlineEditor.RichText.MacroPlugin.Command.InsertDynamicText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back.
        /// </summary>
        internal static string Kentico_InlineEditor_RichText_MacroPlugin_Command_PopupBack {
            get {
                return ResourceManager.GetString("Kentico.InlineEditor.RichText.MacroPlugin.Command.PopupBack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove.
        /// </summary>
        internal static string Kentico_InlineEditor_RichText_MacroPlugin_Command_RemoveMacro {
            get {
                return ResourceManager.GetString("Kentico.InlineEditor.RichText.MacroPlugin.Command.RemoveMacro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to URL parameter.
        /// </summary>
        internal static string Kentico_InlineEditor_RichText_MacroPlugin_Command_UrlParameter {
            get {
                return ResourceManager.GetString("Kentico.InlineEditor.RichText.MacroPlugin.Command.UrlParameter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact attribute.
        /// </summary>
        internal static string Kentico_InlineEditor_RichText_MacroPlugin_Label_ContactAttribute {
            get {
                return ResourceManager.GetString("Kentico.InlineEditor.RichText.MacroPlugin.Label.ContactAttribute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default text.
        /// </summary>
        internal static string Kentico_InlineEditor_RichText_MacroPlugin_Label_DefaultText {
            get {
                return ResourceManager.GetString("Kentico.InlineEditor.RichText.MacroPlugin.Label.DefaultText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to URL parameter.
        /// </summary>
        internal static string Kentico_InlineEditor_RichText_MacroPlugin_Label_UrlParameter {
            get {
                return ResourceManager.GetString("Kentico.InlineEditor.RichText.MacroPlugin.Label.UrlParameter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Full name.
        /// </summary>
        internal static string Kentico_InlineEditor_RichText_MacroPlugin_Pattern_ContactDescriptiveName {
            get {
                return ResourceManager.GetString("Kentico.InlineEditor.RichText.MacroPlugin.Pattern.ContactDescriptiveName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First name.
        /// </summary>
        internal static string Kentico_InlineEditor_RichText_MacroPlugin_Pattern_ContactFirstName {
            get {
                return ResourceManager.GetString("Kentico.InlineEditor.RichText.MacroPlugin.Pattern.ContactFirstName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last name.
        /// </summary>
        internal static string Kentico_InlineEditor_RichText_MacroPlugin_Pattern_ContactLastName {
            get {
                return ResourceManager.GetString("Kentico.InlineEditor.RichText.MacroPlugin.Pattern.ContactLastName", resourceCulture);
            }
        }
    }
}
