name: Notify the internal ticket system when issue or pull request is opened

on: 
  issues:
    types: [opened]

  pull_request:
    types: [opened]

jobs:
  issue-webhook:
    if: github.event_name == 'issues'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
        with:
          fetch-depth: 1
      - name: Send data
        uses: ./.github/actions/web-hook
        with:
          url: ${{ secrets.ISSUES_ENDPOINT }}
  
  pull-request-webhook:
    if: (github.event_name == 'pull_request') && !startsWith(github.event.pull_request.title, 'MAE-') && !startsWith(github.event.pull_request.title, 'CM-')
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
        with:
          fetch-depth: 1
      - name: Send data
        uses: ./.github/actions/web-hook
        with:
          url: ${{ secrets.PULL_REQUEST_ENDPOINT }}

  always_job:
    name: Always run job
    runs-on: ubuntu-latest
    steps:
      - name: Always run
        run: echo "This job is used to prevent the workflow status from showing as failed when all other jobs are skipped."

        
    
